LOAD DATA LOCAL INFILE 'sortUItems.dat' INTO TABLE Items FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'sortUBids.dat' INTO TABLE Bids FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'sortUUsers.dat' INTO TABLE Users FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'sortUCategories.dat' INTO TABLE Categories FIELDS TERMINATED BY '|*|';

